spring:
  application:
    name: store
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        instanceId: ${spring.application.name}:${random.value}
        healthCheckPath: /health
        healthCheckInterval: 5s